spring.application.name=RealTimeFinancialLedgerSystem

spring.datasource.url=jdbc:mysql://localhost:3306/ledgerdb
spring.datasource.username=root
spring.datasource.password=root9099

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=ThisIsAVerySecretKeyForFinancialLedgerSystemProject123456

jwt.expiration=86400000

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG